### ISSUE TITLE
How to use phpvirtualbox...

### ISSUE THREAD

**Issue by jayjupdhig** [phpvirtualbox/phpvirtualbox#245]
a.) Without Flash, but with VM screen in Browser (e.g. with a canvas element, maybe...?)
b.) With secure auth for the VM screen ->  so not just for 127.0.0.1

Thx for feedback.

**Comment by martijintro** [comment]
???

**Comment by martijintro** [comment]
No anwser?!?

**Comment by jayjupdhig** [comment]
problem is still pendent!!

**Comment by h6w** [comment]
a) The client side is not the issue.  Flash allows direct TCP/UDP whereas your browser doesn't, so you need a TCP->WS relay which isn't normal PHP because it isn't stateless.
b) Similar to (a), this is a networking issue with VirtualBox. We don't forward any ports because PHP is stateless.  Look at normal network port forwarding or your Virtualbox configuration.

**Comment by jayjupdhig** [comment]
OK
