### ISSUE TITLE
Ability to use Virtual optical disk from local network

### ISSUE THREAD

**Issue by miksch123** [phpvirtualbox/phpvirtualbox#251]
Hello,

as I was using phpvirtualbox a thought came to me if it would be possible to use virtual disk images for installing VMs that are located on the local network.

I also apologize if there is already something like that documented somewhere.

Any info on that would be greatly appreciated.

**Comment by h6w** [comment]
Your question is a little unclear.

I think what you might be describing is PXE, which is an extension to DHCP which allows the BIOS to run software from the network (and potentially install using that software).  You can install virtual machines from PXE servers just like you can install real machines using PXE boot.

Virtualbox does support PXE client mode, so you can install VMs from a local PXE server.  However, if you want to set up a PXE server that's well outside the scope of the Virtualbox project.

If your PXE server is external to your Virtualbox environment, then you will need to connect your network using bridge mode.  If you build a PXE server on a VM, then you will need to turn off DHCP so that the PXE client knows where to boot from.

**Comment by miksch123** [comment]
Apologies for the poor description.

Am I right in the assumption that when you are in a linux system without having network shares mounted to your Virtualbox system that you are not able to add an iso to a VM using the file picker in phpvirtualbox?

When I try to add an iso disk file to the VM It looks like when I am inside the file picker of phpvirtualbox I am limited to the folders that are on the Virtual Machine host.

I also added a screenshot of the file picker: [https://drive.google.com/file/d/1J74sI7vvhE34JOFf-Sgxwqfew_-D-w3n/view?usp=sharing](here)

**Comment by trasherdk** [comment]
When you interact with `phpVirtualBox`, you are talking to the `host` VirtualBox instance.  
In the case of attaching an ISO to a guest drive, you are telling the `host` to grant access to that file to the `guest`.  
If your `guest` has access to another filesystem, the `host` knows nothing about that.

Does that make sense ?

**Comment by miksch123** [comment]
Thanks for that info. I actually just started to use phpvirtualbox recently and am still setting everything up. To restrict access to certain folders really is a sensible thing to do. I will keep that in mind.

I also found a way of working with OS installation image files that are on another external machine other than the "host's" local file system.
I simply mounted a network share of another machine to my "host". that way I have a central place to store and use my OS image files on phpvirtualbox. In addition I can use that same way on additional vbox "hosts" if there is the need for it.

So when I want to use an OS image from a network share to install an OS on a new VM through phpvirtualbox I can do that.

Thanks for the help. It was really valuable.
