### ISSUE TITLE
Cannot use console with Virtualbox 6.1

### ISSUE THREAD

**Issue by qhuyduong** [phpvirtualbox/phpvirtualbox#268]
Hi,

I'm using Virtualbox 6.1 and phpvirtualbox on master branch. Everything's working fine except the console. It's empty when I click on the console button.
![image](https://user-images.githubusercontent.com/16358771/105985559-309c2100-60ce-11eb-9498-1e9250102f30.png)

Is there any clue for that?

**Comment by h6w** [comment]
Hi,

Adboe Flash Player support has been discontinued by all browsers from December 31, 2020.  It's not our fault and there is no PHP-based solution due to web browsers limiting access to only standard ports.

We recommend instead using Remmina and piping VNC/RDP by using the rdp:// link in the VM detail.

Cheers,
Tudor.

**Comment by qhuyduong** [comment]
Thank you!
