### ISSUE TITLE
There hasn't been an offical relase of PHPVirtualbox in years

### ISSUE THREAD

**Issue by imcdona** [phpvirtualbox/phpvirtualbox#298]
There hasn't been an "official" release of phpvirtualbox since 2018. I'm sure the current owner of this project had good intentions when he took over the project from the original developer, Ian Moore some time ago. As it stands now, it's obvious that the current owner doesn't have the time required to properly maintain this project anymore.

Maybe the current project owner would consider handing this project off to someone else who has the time required to manage this project?

In the meantime, I see there are many forks. Can anyone recommend a good fork that I can start using going forward?

Thanks

**Comment by h6w** [comment]
Are you offering? Otherwise the title of your issue isn't relevant to the question.  I'd strongly suggest reading some material on etiquette when attempting to engage people who do things for you for free.  I.e. Offer to help first before criticising the people who have already done a lot of work for you.

As for not having a release, the development fork still works pretty well, and we encourage people to use it while taking the risk.  But there are some non-trivial issues with being squeezed between PHP and Oracle that present quite a number of functional and  security concerns that make declaring a release a lot more work.  Just because there isn't a release, it doesn't mean we aren't here and active.  We give what we can in the time we have.

**Comment by trasherdk** [comment]
I, for one, would not monitor a libre.chat channel.

With github/issues I get an email, that I can attend to when it suits me.

**Comment by imcdona** [comment]
You wouldn't have to monitor the chat. The chat would be monitored by volunteers such as myself and anyone else who want's to participate. It may also cut down on the number of issues opened for various things that could be addressed in chat.

I've sent a request to https://libera.chat asking for what's required from the owner to get started should they want to proceed.
