### ISSUE TITLE
Is there a version that supports VirtualBox 7.0.0 WITH native HTML5 browser virtual machine screen support?

### ISSUE THREAD

**Issue by jayjupdhig** [phpvirtualbox/phpvirtualbox#314]
"WITH native HTML5 browser virtual machine screen support"

-> Which means equivalant to the flash element as it was before flash was removed.

Thx for feedback(s). :-) 

Best regards, Hans

**Comment by jayjupdhig** [comment]
"WITH native HTML5 browser virtual machine screen support"

**Keywords:**

- HTML5 "Canvas" element
- VNC


(Proxmox is also able to do that  - without any additional browser plugins AND without "mstsc.exe" [or another M$ RDP client])

**Comment by h6w** [comment]
Hi @jayjupdhig,

No.  I've discussed this many times at length in other tickets.  The problem is not with HTML5 support, but with access to RDP ports through the web browser.  Firefox and Chrome both now block all ports except 80 and 443.  RDP is port 3389.  Therefore no client-side console will work (which is all that the Flash console was).

Proxmox and Guacamole do this by running a server-side proxy.  PHP cannot run server-side proxies. Therefore this is impossible within the scope of this project.

Cheers,
Tudor.
