### ISSUE TITLE
Virtualbox 7 + PHP 8.2 = Remote Acess Tab not working

### ISSUE THREAD

**Issue by xxsamxx1991** [phpvirtualbox/phpvirtualbox#322]
On my Ubuntu 22.04 machine with Virtualbox 7.04 the remote access tab is not reachable.

I don't know if the remote access is working with configuration over the terminal.
For this I've to search the right steps to configure it via terminal.

**Comment by BartekSz95** [comment]
Yep, I saw that. _Remote access_ and _Encryption_ tabs doesn't works. I think, something was changed on API. I will check this tomorrow or maybe someone can help with this :)

**Comment by xxsamxx1991** [comment]
I think this lines could be the problem:
`if(!($('#vboxSettingsDialog').data('vboxMachineData').VRDEServer && $('#vboxSettingsDialog').data('vboxMachineData').VRDEServer.VRDEExtPack)) {
        $('#vboxSettingsTabGeneralEncryption').parent().tabs('disable', 3);
    } else {
        $('#vboxSettingsTabGeneralEncryption').parent().tabs('enable', 3);`

Perhaps something on this changed and this lines are in both files present.

**Comment by BartekSz95** [comment]
I moved this issue to my repository:
https://github.com/BartekSz95/phpvirtualbox/issues/1

**Comment by BartekSz95** [comment]
I found the solution. This problem isn't with phpVirtualBox, but with VirtualBox. I spent 2 days to find the problem, but solution was very simple. You need restart whole server, because VBox doesn't refresh info about **Extension Pack** after upgrading it. If you do that, _Remote Access_ and _Encryption_ tabs should start working :)

Screens:
![obraz](https://user-images.githubusercontent.com/79801491/209870931-7666dfd6-59de-4247-ac2e-951c4e9b35b3.png)
![obraz](https://user-images.githubusercontent.com/79801491/209870939-7b7c5c8b-a82c-4d01-8afe-e5dc50304034.png)
